### ISSUE TITLE
#3.3 Architecture Design

### ISSUE THREAD

**Issue by jihoonieeee** [Charlenelzq/INF2001_P8-4#10]
Task: Describe your team’s software architectural design, a diagram to illustrate the architecture design and paragraph to explain the rationale for selecting your chosen design
Goal: Clear architectural diagram
Completion Criteria: Completed architectural diagram

**Comment by lzj1899** [comment]
Started draft on software architecture design using C4 model

**Comment by lzj1899** [comment]
Change software architecture design to hierarchical layered design
Presentation layer:
- Boundary class

Business layer:
- Interface class
- Control class

Data layer:
- Entity class
