### ISSUE TITLE
#3.5 Wireframe

### ISSUE THREAD

**Issue by jihoonieeee** [Charlenelzq/INF2001_P8-4#14]
Task: Create wireframe for web app for the system
Goal: Create wireframe
Completion Criteria: Completed wireframe

**Comment by jihoonieeee** [comment]
Created draft of wireframe

**Comment by Saltified00** [comment]
# Pages Completed
- Login
- IT Admin, Manager, Staff Landing Page
- IT Admin Account Creation and Deletion
- Staff Adding & Editing of Availability

# In-Progress
- Staff Preference
- Creation of Job Assignment
- Allocation of Job Assignment
- View Staff Workload
- Staff Reject Job Assignment

**Comment by Saltified00** [comment]
# Pages Completed
- Login
- IT Admin, Manager, Staff Landing Page
- IT Admin Account Creation and Deletion
- Staff Adding & Editing of Availability
- Staff Preference
- Creation of Job Assignment

# In-Progress
- Allocation of Job Assignment
- View Staff Workload
- Staff Reject Job Assignment
- Alternate Scenarios for all

**Comment by Saltified00** [comment]
# Pages Completed
- Login
- IT Admin, Manager, Staff Landing Page
- IT Admin Account Creation and Deletion
- Staff Adding & Editing of Availability
- Staff Preference
- Creation of Job Assignment
- View Staff Workload

# In-Progress
- Allocation of Job Assignment
- Staff Reject Job Assignment
- Alternate Scenarios for all

**Comment by Saltified00** [comment]
# Pages Completed
- Login
- IT Admin, Manager, Staff Landing Page
- IT Admin Account Creation and Deletion
- Staff Adding & Editing of Availability
- Staff Preference
- Creation of Job Assignment
- View Staff Workload
- Staff Reject Job Assignment

# In-Progress
- Allocation of Job Assignment
- Alternate Scenarios (More or less settled)

**Comment by Saltified00** [comment]
# Pages Completed
- Login
- IT Admin, Manager, Staff Landing Page
- IT Admin Account Creation and Deletion
- Staff Adding & Editing of Availability
- Staff Preference
- Creation of Job Assignment
- View Staff Workload
- Staff Reject Job Assignment
- Allocation of Job Assignment (Settled by Charlene)
- Alternate Scenarios
